#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'learn-lifecyclenode-py==0.0.0','console_scripts','lifecyclenode'
__requires__ = 'learn-lifecyclenode-py==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('learn-lifecyclenode-py==0.0.0', 'console_scripts', 'lifecyclenode')()
    )
